cmake: fix libpng for AARCH64
Cherry-pick of commit
https://github.com/opencv/opencv/commit/bdaab1cee59d20916fb659fa37186af9e39da076

This fixes [issue #7600][1] which is a linker error

```
libopencv_imgcodecs.so.3.1.0: undefined reference to
`png_init_filter_functions_neon'
```

[1]: https://github.com/opencv/opencv/issues/7600#issuecomment-258358113